version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '4000:4000'
    depends_on:
      - fiap-tech-challenge-db
  fiap-tech-challenge-db:
    image: postgres
    container_name: fiap-tech-challenge-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=fiap-tech-challenge
    ports:
      - '5432:5432'
networks:
  default:
    driver: bridge
