version: '3.8'
services:
  fiap-tech-challenge-api:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: fiap-tech-challenge-api
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    depends_on:
      - fiap-tech-challenge-db
  fiap-tech-challenge-db:
    image: postgres
    container_name: fiap-tech-challenge-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=fiap-tech-challenge
    ports:
      - '5432:5432'
volumes:
  data:
    driver: local
